
default: &default
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_api_development
 

test:
  <<: *default
  database: restaurant_api_test

production:
  <<: *default
  database: restaurant_api_production
  username: restaurant_api
  password: <%= ENV["RESTAURANT_API_DATABASE_PASSWORD"] %>
