
default: &default
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
